# Generated by Django 5.1 on 2024-08-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receiptrequest",
            options={
                "verbose_name": "чекова вимога",
                "verbose_name_plural": "чекові вимоги",
            },
        ),
        migrations.AlterModelOptions(
            name="receiptrequestcoupon",
            options={
                "verbose_name": "талон чекової вимоги",
                "verbose_name_plural": "талони чекових вимог",
            },
        ),
    ]
