# Generated by Django 5.1 on 2024-08-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0008_vidom_sender"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Atestat",
            new_name="Certificate",
        ),
        migrations.RenameModel(
            old_name="Vidom",
            new_name="SummaryReport",
        ),
    ]
