# Generated by Django 5.1 on 2024-08-31 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('receipts', '0009_rename_atestat_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryreport',
            name='departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='підрозділ'),
        ),
    ]
