# Generated by Django 5.1 on 2024-08-31 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0010_summaryreport_departments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summaryreport",
            name="departments",
        ),
    ]
