# Generated by Django 5.1 on 2024-09-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0012_remove_summaryreport_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptrequest",
            name="scan",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="receiptrequestcoupon",
            name="scan",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
