# Generated by Django 5.1 on 2024-09-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0013_receiptrequest_scan_receiptrequestcoupon_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptrequest',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Скан'),
        ),
        migrations.AlterField(
            model_name='receiptrequestcoupon',
            name='scan',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Скан'),
        ),
    ]
