# Generated by Django 5.1 on 2024-09-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0015_reporting_certificate_document_date_certificate_scan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='номер'),
        ),
    ]
