# Generated by Django 5.1 on 2024-09-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0020_alter_reporting_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='operation_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата операції'),
        ),
    ]
