# Generated by Django 5.1 on 2024-09-11 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0023_reportingsummaryreport_reporting_summary_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporting",
            name="summary_report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reportings",
                to="receipts.reportingsummaryreport",
            ),
        ),
    ]
