# Generated by Django 5.1 on 2024-10-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0027_remove_invoice_end_date_remove_invoice_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="receiver",
            new_name="destination",
        ),
    ]
