# Generated by Django 5.1 on 2024-10-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0029_invoicesummaryreport_invoice_summary_report'),
        ('summary_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='summary_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='summary_reports.invoicesummaryreport'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='summary_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportings', to='summary_reports.reportingsummaryreport'),
        ),
        migrations.DeleteModel(
            name='InvoiceSummaryReport',
        ),
        migrations.DeleteModel(
            name='ReportingSummaryReport',
        ),
    ]
