# Generated by Django 5.1 on 2024-10-07 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0030_alter_invoice_summary_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falreportentry',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fals', to='receipts.reporting'),
        ),
    ]
