# Generated by Django 5.1 on 2024-10-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0031_alter_falreportentry_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='falreportentry',
            name='outcome_own',
            field=models.FloatField(blank=True, null=True, verbose_name='вибуло(власна частина)'),
        ),
    ]
