# Generated by Django 5.1 on 2024-10-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0032_falreportentry_outcome_own'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falreportentry',
            name='outcome_own',
        ),
    ]
