# Generated by Django 5.1 on 2024-10-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0033_remove_falreportentry_outcome_own"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="falreportentry",
            name="density",
        ),
    ]
