# Generated by Django 5.1 on 2024-10-16 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0010_warehouse_order"),
        ("receipts", "0034_remove_falreportentry_density"),
    ]

    operations = [
        migrations.CreateModel(
            name="HandoutList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50, verbose_name="номер")),
                (
                    "document_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата документу"
                    ),
                ),
                (
                    "scan",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Скан"
                    ),
                ),
                ("operation_date", models.DateField(verbose_name="дата операції")),
                ("start_date", models.DateField(verbose_name="початкова дата")),
                ("end_date", models.DateField(verbose_name="кінцева дата")),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handout_receiver",
                        to="departments.department",
                        verbose_name="отримувач",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hadout_sender",
                        to="departments.department",
                        verbose_name="відправник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роздавальна відомість",
                "verbose_name_plural": "Роздавальні відомості",
            },
        ),
    ]
