# Generated by Django 5.1 on 2024-10-22 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0035_handoutlist"),
        ("summary_reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="summary_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="summary_reports.invoicesummaryreport",
                verbose_name="Звередна відомість",
            ),
        ),
    ]
