# Generated by Django 5.1 on 2024-10-25 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0037_handoutlist_summary_report'),
        ('summary_reports', '0002_handoutlistsummaryreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoutlist',
            name='summary_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handout_lists', to='summary_reports.handoutlistsummaryreport'),
        ),
    ]
