# Generated by Django 5.1 on 2024-10-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0038_alter_handoutlist_summary_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="falreportentry",
            name="density",
            field=models.FloatField(blank=True, null=True, verbose_name="густина"),
        ),
    ]
