# Generated by Django 5.1 on 2024-10-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0039_falreportentry_density"),
    ]

    operations = [
        migrations.CreateModel(
            name="WritingOffAct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50, verbose_name="номер")),
                (
                    "document_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата документу"
                    ),
                ),
                (
                    "scan",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Скан"
                    ),
                ),
                (
                    "operation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата операції"
                    ),
                ),
            ],
            options={
                "verbose_name": "акт списання",
                "verbose_name_plural": "акти списання",
            },
        ),
    ]
