# Generated by Django 5.1 on 2024-10-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0040_writingoffact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writingoffact",
            name="number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="номер"
            ),
        ),
    ]
