# Generated by Django 5.1 on 2024-10-27 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0010_warehouse_order"),
        ("receipts", "0041_alter_writingoffact_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=50, verbose_name="номер")),
                (
                    "document_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата документу"
                    ),
                ),
                (
                    "scan",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Скан"
                    ),
                ),
                ("operation_date", models.DateField(verbose_name="дата операції")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.department",
                        verbose_name="підрозділ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Інспекторське Посвідчення",
                "verbose_name_plural": "Інспекторські Посвідчення",
            },
        ),
    ]
