# Generated by Django 5.1 on 2024-11-03 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0045_invoiceforrrc_alter_reporting_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceforrrcentry",
            name="rrc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fals",
                to="receipts.invoiceforrrc",
            ),
        ),
    ]
