# Generated by Django 5.1 on 2024-11-03 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0046_alter_invoiceforrrcentry_rrc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoiceforrrcentry",
            old_name="rrc",
            new_name="invoice_for_rrc",
        ),
        migrations.AddField(
            model_name="invoiceforrrc",
            name="rrc",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fals",
                to="receipts.receiptrequestcoupon",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoiceforrrcentry",
            name="price",
            field=models.FloatField(default=0, verbose_name="сума (в грн)"),
            preserve_default=False,
        ),
    ]
