# Generated by Django 5.1 on 2024-11-03 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0047_rename_rrc_invoiceforrrcentry_invoice_for_rrc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceforrrc",
            name="rrc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="receipts.receiptrequestcoupon",
            ),
        ),
    ]
