# Generated by Django 5.1 on 2024-11-04 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0048_alter_invoiceforrrc_rrc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceforrrc",
            name="rrc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="receipts.receiptrequestcoupon",
            ),
        ),
    ]
