# Generated by Django 5.1 on 2024-11-27 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0050_invoiceforrrc_certificate"),
        ("summary_reports", "0002_handoutlistsummaryreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reporting",
            name="waybills_count",
        ),
        migrations.AddField(
            model_name="reporting",
            name="handout_numbers",
            field=models.TextField(
                blank=True, null=True, verbose_name="кількість шляхових"
            ),
        ),
        migrations.AddField(
            model_name="reporting",
            name="waybills_numbers",
            field=models.TextField(
                blank=True, null=True, verbose_name="кількість шляхових"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="summary_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="summary_reports.invoicesummaryreport",
                verbose_name="зведена відомість",
            ),
        ),
    ]
