# Generated by Django 5.1 on 2024-11-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0051_remove_reporting_waybills_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporting",
            name="handout_numbers",
            field=models.TextField(
                blank=True, null=True, verbose_name="номера роздавальних відомостей"
            ),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="waybills_numbers",
            field=models.TextField(
                blank=True, null=True, verbose_name="номера шляхових"
            ),
        ),
    ]
