# Generated by Django 5.1 on 2024-11-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0052_alter_reporting_handout_numbers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporting",
            name="number",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="номер"
            ),
        ),
    ]
