# Generated by Django 5.1 on 2024-12-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0053_alter_reporting_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handoutlist",
            name="number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="номер"
            ),
        ),
    ]
