# Generated by Django 5.1 on 2024-12-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0054_alter_handoutlist_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handoutlist",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="кінцева дата"),
        ),
        migrations.AlterField(
            model_name="handoutlist",
            name="start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="початкова дата"
            ),
        ),
    ]
