# Generated by Django 5.1 on 2024-12-10 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0011_department_chief_name_department_chief_position"),
        ("receipts", "0055_alter_handoutlist_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporting",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportings",
                to="departments.department",
                verbose_name="підрозділ",
            ),
        ),
    ]
