# Generated by Django 5.1 on 2024-12-11 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fals", "0010_alter_faltype_density"),
        ("receipts", "0056_alter_reporting_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceforrrcentry",
            name="fal_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fal_rrc_entries",
                related_query_name="fal_rrc_entries",
                to="fals.faltype",
                verbose_name="тип",
            ),
        ),
    ]
