# Generated by Django 5.1 on 2025-01-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0059_alter_handoutlist_destination_and_more"),
        ("summary_reports", "0003_handoutlistsummaryreport_record_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="record_date",
            field=models.DateField(blank=True, null=True, verbose_name="дата запису"),
        ),
        migrations.AddField(
            model_name="handoutlist",
            name="record_date",
            field=models.DateField(blank=True, null=True, verbose_name="дата запису"),
        ),
        migrations.AddField(
            model_name="inspectioncertificate",
            name="record_date",
            field=models.DateField(blank=True, null=True, verbose_name="дата запису"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="record_date",
            field=models.DateField(blank=True, null=True, verbose_name="дата запису"),
        ),
        migrations.AddField(
            model_name="invoiceforrrc",
            name="record_date",
            field=models.DateField(blank=True, null=True, verbose_name="дата запису"),
        ),
        migrations.AddField(
            model_name="receiptrequest",
            name="record_date",
            field=models.DateField(blank=True, null=True, verbose_name="дата запису"),
        ),
        migrations.AddField(
            model_name="receiptrequestcoupon",
            name="record_date",
            field=models.DateField(blank=True, null=True, verbose_name="дата запису"),
        ),
        migrations.AddField(
            model_name="reporting",
            name="record_date",
            field=models.DateField(blank=True, null=True, verbose_name="дата запису"),
        ),
        migrations.AddField(
            model_name="writingoffact",
            name="record_date",
            field=models.DateField(blank=True, null=True, verbose_name="дата запису"),
        ),
        migrations.AlterField(
            model_name="handoutlist",
            name="summary_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handout_lists",
                to="summary_reports.handoutlistsummaryreport",
                verbose_name="зведена відомість",
            ),
        ),
    ]
