# Generated by Django 5.1 on 2025-01-09 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0060_certificate_record_date_handoutlist_record_date_and_more"),
        ("summary_reports", "0003_handoutlistsummaryreport_record_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handoutlist",
            name="summary_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="summary_reports.handoutlistsummaryreport",
                verbose_name="зведена відомість",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="summary_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="summary_reports.invoicesummaryreport",
                verbose_name="зведена відомість",
            ),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="summary_report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="summary_reports.reportingsummaryreport",
            ),
        ),
    ]
