# Generated by Django 5.1 on 2025-05-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0061_alter_handoutlist_summary_report_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporting",
            name="number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="номер"
            ),
        ),
    ]
