# Generated by Django 5.1 on 2025-05-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0062_alter_reporting_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="falreportentry",
            name="outcome_burned",
            field=models.FloatField(default=0, verbose_name="спалено (кг)"),
            preserve_default=False,
        ),
    ]
