# Generated by Django 5.1 on 2025-05-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0063_falreportentry_outcome_burned"),
    ]

    operations = [
        migrations.AddField(
            model_name="falreportentry",
            name="outcome_burned_ltr",
            field=models.FloatField(default=0, verbose_name="спалено (л)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="falreportentry",
            name="income",
            field=models.FloatField(verbose_name="надійшло (л)"),
        ),
        migrations.AlterField(
            model_name="falreportentry",
            name="remains",
            field=models.FloatField(verbose_name="залишок (л)"),
        ),
    ]
