# Generated by Django 5.1 on 2024-08-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FALType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="ім'я")),
                (
                    "year_in_school",
                    models.CharField(
                        choices=[
                            ("OIL", "мастило"),
                            ("DIESEL", "дизель"),
                            ("PETROL", "бензин"),
                            ("POISON", "отрута"),
                        ],
                        default="OIL",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип ПММ",
                "verbose_name_plural": "Типи ПММ",
            },
        ),
        migrations.CreateModel(
            name="FAL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="кількість")),
                (
                    "fal_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fals.faltype",
                        verbose_name="тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пально-мастильний матеріал",
                "verbose_name_plural": "Пально-мастильнi матеріали",
            },
        ),
    ]
