# Generated by Django 5.1 on 2024-08-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faltype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="ім'я"),
        ),
    ]
