# Generated by Django 5.1 on 2024-08-23 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fals', '0002_alter_faltype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fal',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='fal',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
