# Generated by Django 5.1 on 2024-08-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fals", "0003_fal_content_type_fal_object_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faltype",
            old_name="year_in_school",
            new_name="category",
        ),
    ]
