# Generated by Django 5.1 on 2024-09-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fals', '0005_alter_faltype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fal',
            name='fal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fals', to='fals.faltype', verbose_name='тип'),
        ),
    ]
