# Generated by Django 5.1 on 2024-10-10 07:56

from django.db import migrations


def update_denisty_for_petrol_and_oil(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    FALType = apps.get_model("fals", "FALType")
    for ft in FALType.objects.all():
        if ft.category == 'OIL':
            ft.density = 0.9
        elif ft.category == 'PETROL':
            ft.density = 0.75
        ft.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fals', '0007_faltype_density'),
    ]

    operations = [
        migrations.RunPython(update_denisty_for_petrol_and_oil),
    ]
