# Generated by Django 5.1 on 2024-10-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fals", "0008_auto_20241010_0756"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faltype",
            name="category",
            field=models.CharField(
                choices=[
                    ("OIL", "мастило"),
                    ("DIESEL", "дизель"),
                    ("PETROL", "бензин"),
                    ("POISON", "отрута"),
                    ("KEROSENE", "керосин"),
                ],
                default="OIL",
                max_length=20,
                verbose_name="категорія",
            ),
        ),
    ]
