# Generated by Django 5.1 on 2024-11-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fals", "0009_alter_faltype_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faltype",
            name="density",
            field=models.FloatField(default=0, verbose_name="густина"),
        ),
    ]
