# Generated by Django 5.1 on 2024-08-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_departmententity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmententity',
            old_name='departments',
            new_name='department',
        ),
    ]
