# Generated by Django 5.1 on 2024-09-12 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmententity',
            name='summary_report',
        ),
    ]
