# Generated by Django 5.1 on 2024-12-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0010_warehouse_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="chief_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ім'я командира"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="chief_position",
            field=models.CharField(
                choices=[("CHIEF", "Командир"), ("TEMP_CHIEF", "ТВО Командира")],
                default="CHIEF",
                max_length=20,
                verbose_name="посада командира",
            ),
        ),
    ]
