# Generated by Django 5.1 on 2025-01-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summary_reports", "0002_handoutlistsummaryreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="handoutlistsummaryreport",
            name="record_date",
            field=models.DateField(blank=True, null=True, verbose_name="дата запису"),
        ),
        migrations.AddField(
            model_name="invoicesummaryreport",
            name="record_date",
            field=models.DateField(blank=True, null=True, verbose_name="дата запису"),
        ),
        migrations.AddField(
            model_name="reportingsummaryreport",
            name="record_date",
            field=models.DateField(blank=True, null=True, verbose_name="дата запису"),
        ),
    ]
